# Generated by Django 6.0.5 on 2026-06-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwalimuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='degree_url',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/degree/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='national_id_url',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/id/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='tsc_cert_url',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/tsc/'),
        ),
    ]
